'use client';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {RoundedBox} from '@react-three/drei/core/RoundedBox';
import {useRef,useEffect,useMemo,useLayoutEffect,useState} from 'react';
import * as THREE from 'three';
import {projects} from '@/lib/projects';
import {cartridgeRests,consoleZoom} from '@/lib/console-layout';
import CartridgeLabel from './cartridge-label';
import {flightPose,seatedPose,FLIGHT_MS,type CartridgeMotion,type Pose} from '@/lib/cartridge-motion';
import type {PressedControl} from './console-controls';
type Props={active:number|null;motion:CartridgeMotion|null;filter:string;compact:boolean;reduced:boolean;select:(i:number)=>void;pressed:PressedControl;onReady:()=>void};
function Bevel({size,position=[0,0,0],color,radius=.06,metalness=.05,roughness=.5}:{size:[number,number,number];position?:[number,number,number];color:string;radius?:number;metalness?:number;roughness?:number}){return <RoundedBox args={size} position={position} radius={radius} smoothness={2}><meshStandardMaterial color={color} roughness={roughness} metalness={metalness}/></RoundedBox>;}
function Screw({x,y}:{x:number;y:number}){return <group position={[x,y,.355]}><mesh rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.041,.041,.017,16]}/><meshStandardMaterial color="#9b9b8b" metalness={.8} roughness={.28}/></mesh><mesh position={[0,0,.013]} rotation={[0,0,.6]}><boxGeometry args={[.047,.009,.005]}/><meshBasicMaterial color="#424a39"/></mesh></group>;}
function PhysicalButton({position,pressed}:{position:[number,number,number];pressed:boolean}){
 const cap=useMemo(()=>new THREE.LatheGeometry([new THREE.Vector2(0,0),new THREE.Vector2(.16,0),new THREE.Vector2(.187,.018),new THREE.Vector2(.19,.043),new THREE.Vector2(.182,.07),new THREE.Vector2(.15,.089),new THREE.Vector2(0,.095)],48),[]);
 useEffect(()=>()=>cap.dispose(),[cap]);
 return <group position={position}><mesh rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.218,.218,.028,40]}/><meshStandardMaterial color="#6d4835" roughness={.56}/></mesh><mesh position={[0,0,.018]}><torusGeometry args={[.202,.015,8,40]}/><meshStandardMaterial color="#b7aa8c" roughness={.32} metalness={.55}/></mesh><mesh rotation={[Math.PI/2,0,0]} position={[0,0,pressed?-.016:.018]} geometry={cap}><meshStandardMaterial color="#dc6536" roughness={.28} metalness={.18}/></mesh></group>;
}
function DPad({pressed}:{pressed:PressedControl}){const geometry=useMemo(()=>{const w=.125,l=.43;const s=new THREE.Shape();s.moveTo(-w,l);s.lineTo(w,l);s.lineTo(w,w);s.lineTo(l,w);s.lineTo(l,-w);s.lineTo(w,-w);s.lineTo(w,-l);s.lineTo(-w,-l);s.lineTo(-w,-w);s.lineTo(-l,-w);s.lineTo(-l,w);s.lineTo(-w,w);s.closePath();return new THREE.ExtrudeGeometry(s,{depth:.07,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.02,bevelThickness:.018});},[]);useEffect(()=>()=>geometry.dispose(),[geometry]);return <group position={[-.74,-1.22,.38]}><mesh rotation={[Math.PI/2,0,0]} position={[0,0,-.015]}><cylinderGeometry args={[.46,.46,.025,40]}/><meshStandardMaterial color="#b8b4a3" roughness={.8}/></mesh><mesh geometry={geometry} position={[0,0,.025]} rotation={[pressed==='up'?-.07:pressed==='down'?.07:0,pressed==='previous'?-.07:pressed==='next'?.07:0,0]}><meshStandardMaterial color="#30342e" roughness={.4} metalness={.15}/></mesh><mesh position={[0,0,.119]}><circleGeometry args={[.073,24]}/><meshStandardMaterial color="#3e4439" roughness={.55}/></mesh></group>;}
function Hardware({pressed}:Props){return <group><Bevel size={[2.64,4.6,.45]} color="#4c603c" radius={.23} metalness={.2} roughness={.35}/><Bevel size={[2.51,4.5,.3]} position={[0,0,.12]} color="#ddd8c8" radius={.2}/><Bevel size={[2.38,4.35,.055]} position={[0,.01,.31]} color="#eee8d8" radius={.18} roughness={.65}/><Bevel size={[2.2,2.78,.065]} position={[0,.7,.357]} color="#b4b3a1" radius={.12}/><Bevel size={[2.13,2.7,.06]} position={[0,.7,.393]} color="#2c3329" radius={.1}/><Bevel size={[1.97,2.43,.025]} position={[0,.7,.429]} color="#304721" radius={.05}/><Bevel size={[1.14,.07,.15]} position={[0,2.28,0]} color="#15291b" radius={.025}/>{[-1.12,1.12].map(x=>[-2.02,2.02].map(y=><Screw key={x+','+y} x={x} y={y}/>))}<DPad pressed={pressed}/><PhysicalButton position={[.42,-1.33,.36]} pressed={pressed==='back'}/><PhysicalButton position={[.94,-1.1,.36]} pressed={pressed==='open'}/>{[-.2,.2].map((x,i)=><group key={x} position={[x,-1.87,.37]}><Bevel size={[.32,.16,.035]} color="#a5a58d" radius={.045}/><Bevel size={[.27,.105,.065]} position={[0,0,pressed===(i===0?'menu':'start')?.009:.037]} color="#7e8972" radius={.044} metalness={.45} roughness={.28}/></group>)}{[-1,1].map(sign=>Array.from({length:12},(_,i)=><mesh key={sign+','+i} position={[sign*.85+(i%4-1.5)*.075,-1.9+Math.floor(i/4)*.07,.35]}><circleGeometry args={[.017,8]}/><meshBasicMaterial color="#45523a"/></mesh>))}{[-1,1].map(sign=>Array.from({length:6},(_,i)=><mesh key={sign+'c'+i} position={[sign*1.277,-1.5+i*.54,.19]}><boxGeometry args={[.027,.17,.01]}/><meshStandardMaterial color={i%2?'#9a9b70':'#b69f66'} metalness={.6} roughness={.4}/></mesh>))}</group>;}
function CameraFit({compact,onReady}:{compact:boolean;onReady:()=>void}){const {camera,size,invalidate}=useThree();const notified=useRef(false);useLayoutEffect(()=>{if(camera instanceof THREE.OrthographicCamera){camera.rotation.set(0,0,0);camera.zoom=consoleZoom(size.width,size.height,compact);camera.updateProjectionMatrix();invalidate();}},[camera,size,compact,invalidate]);useFrame(()=>{if(!notified.current){notified.current=true;requestAnimationFrame(onReady);}});return null;}

function Cartridge({i,...props}:Props&{i:number}){
 const {active,motion,compact,reduced,filter,select}=props;const seated=active===i;const matches=filter==='All'||projects[i].category===filter;const ref=useRef<THREE.Group>(null);const [hover,setHover]=useState(false);const {invalidate}=useThree();
 const gold=useRef<THREE.InstancedMesh>(null);const hoverY=useRef(0);useLayoutEffect(()=>{if(!gold.current)return;const matrix=new THREE.Matrix4();for(let j=0;j<10;j++){matrix.makeTranslation(-.27+j*.06,-.47,.077);gold.current.setMatrixAt(j,matrix);}gold.current.instanceMatrix.needsUpdate=true;},[]);
 useFrame(()=>{if(!ref.current)return;const moving=motion&&(motion.from===i||motion.to===i);const rest:Pose={position:compact?[-1.05,3.1,.15]:[...cartridgeRests[i]],rotation:[-.25,0,[-.16,.12,.13,-.2,.06,-.12,.18,.14,-.1,.13][i]],scale:1};const elapsed=motion?Math.min(FLIGHT_MS,performance.now()-motion.started):0;const p=moving?flightPose(rest,elapsed,motion.to===i):seated?seatedPose:rest;
 ref.current.visible=Boolean(moving||seated||(!compact&&matches))&&!(compact&&motion?.to===i&&elapsed<1180);
 const targetY=(!moving&&!seated&&hover)?.12:0;
 hoverY.current+=(targetY-hoverY.current)*0.13;
 ref.current.position.set(p.position[0],p.position[1]+hoverY.current,p.position[2]);ref.current.rotation.set(...p.rotation);ref.current.scale.setScalar(p.scale);
 if(motion||Math.abs(targetY-hoverY.current)>0.0004)invalidate();});
 useEffect(()=>{invalidate();},[active,motion,hover,filter,reduced,compact,invalidate]);
 return <group ref={ref} onClick={e=>{e.stopPropagation();select(i);}} onPointerOver={e=>{e.stopPropagation();setHover(true);}} onPointerOut={()=>setHover(false)}><Bevel size={[.82,.99,.14]} color={projects[i].color} radius={.045} roughness={.46}/><Bevel size={[.75,.85,.025]} position={[0,0,.08]} color="#d1ccba" radius={.025}/><CartridgeLabel index={i}/><mesh position={[0,.419,.078]}><boxGeometry args={[.7,.065,.025]}/><meshStandardMaterial color={projects[i].color} roughness={.5}/></mesh><mesh position={[0,-.475,.07]}><boxGeometry args={[.66,.092,.02]}/><meshStandardMaterial color="#3e4536"/></mesh><instancedMesh ref={gold} args={[undefined,undefined,10]}><boxGeometry args={[.035,.07,.012]}/><meshStandardMaterial color="#d4b56c" metalness={.7} roughness={.28}/></instancedMesh></group>;
}
export default function ConsoleScene(props:Props){return <Canvas orthographic camera={{position:[0,.45,12],zoom:100,near:.1,far:40}} dpr={[1,1.35]} frameloop="demand" gl={{antialias:true,alpha:true,powerPreference:'high-performance'}} onCreated={({gl})=>gl.domElement.setAttribute('aria-label','3D console and project cartridges')}><CameraFit compact={props.compact} onReady={props.onReady}/><ambientLight intensity={1.05}/><directionalLight position={[-3,6,8]} intensity={2.7} color="#fff3dc"/><directionalLight position={[4,-1,5]} intensity={.65} color="#c5d9ba"/><Hardware {...props}/>{projects.map((_,i)=><Cartridge key={i} i={i} {...props}/>)}</Canvas>;}
