import originalArticles from './original-blog-posts.json';
export {projects,contact,type Project} from './projects';
export type Article = { slug:string; title:string; category:string; date:string; color:string; intro:string; sections:{heading:string;body:string}[]; };
const articleSeeds: Article[] = [
 {slug:'rethinking-full-stack',title:'Why I Switched to Next.js 14 and Server Actions for My Latest Project',category:'Development',date:'2026-02-25',color:'olive',intro:'I used to rely heavily on separate backend APIs. Now, with Next.js 14 and Server Actions, I’ve completely rethought my approach to full-stack development.',sections:[{heading:'A familiar starting point',body:'When I first started building full-stack applications, the standard practice was clear: build a React frontend, spin up a Node.js or Python backend, and connect them via REST or GraphQL. That was my workflow for years. But recently, I decided to take the plunge into Next.js 14 and its highly talked-about feature: Server Actions.'},{heading:'A different way to work',body:'The moment I realized I could securely mutate data directly from my React components without writing endless API routes, my mind was blown. I found myself deleting dozens of boilerplate fetch calls and API endpoint files. The reduction in context switching alone has made me significantly more productive.'},{heading:'What stayed with me',body:'While the mental model shift took a weekend to click, I now feel like I’m writing the most cohesive code of my career. The performance gains from Server Components combined with the simplicity of Server Actions have convinced me that this is the definitive future of React development.'}]},
 {slug:'ai-in-my-workflow',title:'How I Use AI Tools to 10x My Coding Speed',category:'AI',date:'2026-02-18',color:'rust',intro:'My honest thoughts on integrating GitHub Copilot and ChatGPT into my daily workflow, and how it shifted my focus from syntax to architecture.',sections:[]},
 {slug:'building-on-solana',title:'My Journey Building a dApp on the Solana Blockchain',category:'Web3',date:'2026-02-10',color:'sand',intro:'Moving from traditional Web2 to Web3 was a steep learning curve. Here’s my experience building my first decentralized application on Solana.',sections:[]},
 {slug:'edge-deployment',title:'Why I Believe Edge Computing is the Future of Web Deployment',category:'Cloud',date:'2026-01-28',color:'olive',intro:'Saying goodbye to traditional centralized servers. How deploying to the edge changed my approach to latency and reliability.',sections:[]},
 {slug:'designing-with-ai',title:'How I Design Premium UIs Faster with AI Generators',category:'Design',date:'2026-01-15',color:'rust',intro:'Generative UI tools are changing frontend development. How I use them to explore interfaces and build prototypes.',sections:[]},
 {slug:'exploring-webassembly',title:'My Experience Exploring WebAssembly for High-Performance Browser Apps',category:'WebAssembly',date:'2026-01-02',color:'sand',intro:'Exploring WebAssembly and Rust for computationally heavy web features.',sections:[]},
];
export const articles: Article[] = articleSeeds.map((seed,i)=>({...seed,title:originalArticles[i].title,date:originalArticles[i].date,intro:originalArticles[i].excerpt,sections:originalArticles[i].content.split(/\n\s*\n/).map((body,j)=>({heading:j===0?'The starting point':'What I learned',body:body.trim()}))}));
export function dateLabel(date:string) { return new Date(date+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}); }
export function readTime(a:Article) { return Math.max(1,Math.ceil((a.intro+' '+a.sections.map(s=>s.body).join(' ')).split(/\s+/).length/200)); }
