export type Project = {
  id: string; name: string; short: string; category: 'Web apps' | 'AI' | 'Web3';
  color: string; description: string; stack: string[]; features: string[];
  repo: string; demo?: string; idea: string;
};
export const projects: Project[] = [
  { id:'duma-drones', name:'Duma Drones', short:'DELIVERY, REIMAGINED', category:'Web apps', color:'#526449', description:'Everyday essentials, delivered with speed and precision.', stack:['Python','Django','HTML','CSS'], features:['Browse meals and everyday essentials','Explore a delivery-first shopping experience','Connect people with the things they need'], repo:'DumaDrones', idea:'Make meals, groceries and care packages easier to access through one delivery platform.' },
  { id:'assessly', name:'Assessly', short:'LEARN. TEST. GROW.', category:'Web apps', color:'#c27454', description:'An exam and assessment platform for creating tests and understanding results.', stack:['React','TypeScript','Express','Prisma'], features:['Create and manage exams','Take timed assessments','Review performance and download reports'], repo:'Assesly', demo:'https://assesly.netlify.app', idea:'Bring exam creation, test taking and results into one place, with dedicated experiences for administrators and learners.' },
  { id:'educred', name:'EduCred', short:'CREDENTIALS YOU CAN TRUST', category:'Web3', color:'#b19550', description:'Decentralized certificate issuance and verification on Cardano’s preprod testnet.', stack:['JavaScript','Cardano','Web3'], features:['Issue certificate NFTs','Record document hashes','Verify credentials against their original documents'], repo:'Edu_Cred', idea:'Explore how verifiable digital credentials can make certificate checks more transparent.' },
  { id:'genesis', name:'Genesis', short:'IDEAS INTO POSSIBILITY', category:'Web3', color:'#b76544', description:'A Web3 crowdfunding platform built on Ethereum.', stack:['React','Solidity','Ethereum'], features:['Explore crowdfunding campaigns','Connect a Web3 wallet','Use smart contracts for crowdfunding'], repo:'Project_Genesis', idea:'Explore a more transparent way to support ideas through blockchain-based crowdfunding.' },
  { id:'ivybanking', name:'IvyBanking', short:'BANKING, SIMPLIFIED', category:'Web apps', color:'#626a62', description:'A modern banking application with a focus on a clear digital experience.', stack:['TypeScript','Next.js'], features:['Explore a modern banking interface','Navigate financial information','A web-first banking experience'], repo:'Bank_Application', idea:'Bring a thoughtful interface to the everyday experience of digital banking.' },
  { id:'school-inventory', name:'School Inventory', short:'A PLACE FOR EVERYTHING', category:'Web apps', color:'#667449', description:'Inventory and order management for schools and organizations.', stack:['PHP','MySQL','Bootstrap','jQuery'], features:['Track inventory','Manage orders','Generate PDF invoices'], repo:'School-Inventory-Management-System', idea:'Help schools keep track of resources and organize the daily work around inventory.' },
  { id:'msingi', name:'msingi', short:'FIND YOUR NEXT AHA.', category:'AI', color:'#acaa87', description:'A learning platform where search leads to the moment a topic is taught.', stack:['Next.js','TypeScript','Sanity'], features:['Browse structured courses','Search lessons in plain language','Jump to the relevant moment in a video'], repo:'msingi-learning-platform', idea:'Make it easier to find the right explanation inside a course, rather than scrubbing through entire lessons.' },
  { id:'intellex', name:'Intellex', short:'CURIOSITY, CONNECTED', category:'AI', color:'#a76b55', description:'An AI research assistant built around document retrieval and semantic search.', stack:['Python','RAG','Semantic search'], features:['Work with research documents','Find relevant context','Explore context-aware answers'], repo:'Intellex', idea:'Connect questions to the knowledge within documents using retrieval-augmented generation.' },
  { id:'job-app-tailor', name:'Job App Tailor', short:'YOUR NEXT CHAPTER', category:'AI', color:'#6b7868', description:'An AI tool for tailoring job applications to role descriptions.', stack:['Python','Gemini AI'], features:['Analyze job descriptions','Adapt application material to a role','Support applications across different sectors'], repo:'job-app-tailor', idea:'Make the application process more focused by connecting a candidate’s experience to the role they want.' },
  { id:'stakepesa', name:'StakePesa', short:'SHOW UP. TOGETHER.', category:'Web apps', color:'#c89943', description:'A peer-to-peer accountability platform created for friends.', stack:['TypeScript'], features:['Make commitments with friends','Support shared accountability','Stay connected around your goals'], repo:'StakePesa', idea:'Explore how a shared commitment can help friends follow through on the things they want to do.' },
];
export const contact = { email:'lemayanleleina@gmail.com', phone:'+254 715 197 671', tel:'+254715197671', github:'https://github.com/lemayan', whatsapp:'https://wa.me/254715197671', resume:'https://www.lemayanleleina.engineer/assets/LELEINA%20DENNIS_LEMAYAN_CV.pdf' };
